### ISSUE TITLE
WIFI_STATUS_PIN and WIFI_AP_PIN

### ISSUE THREAD

**Issue by thijstriemstra** [graham22/SkyeTracker#12]
What are the pins `WIFI_STATUS_PIN` and `WIFI_AP_PIN` being used for?

See https://github.com/graham22/SkyeTracker/blob/master/code/ESP32/SkyeTracker/platformio.ini#L51

**Comment by graham22** [comment]
Those can be removed,
the IotWebConf library has options to set the status and AP pins to indicate and trigger AP mode.
the code currently uses setApTimeoutMs(30000) instead.

**Comment by thijstriemstra** [comment]
> Those can be removed,

Ok, will do.

**Comment by thijstriemstra** [comment]
see #13
