### ISSUE TITLE
Checking for movements

### ISSUE THREAD

**Issue by sgamix** [graham22/SkyeTracker#21]
Hi, I downloaded your project and I must say it is fantastic. I don't have all the materials you used, for example I don't have linear motors but I simulated the outputs by connecting LEDs to see how it behaves. 
I noticed that after some time the program sends the movements. 
The questions are: 
How long does it take between chasing? 
Which sensors are needed to know the status of the trak? 

The last question is for a safety issue, putting the case of not using linear motors but simply normal 24V dc gearmotors. 
How do I know how the traker is moving and where it got there? 

Another question, is it possible to remove the configuration via the Android App and simply use the Arduino Sketch ?? 
This question is why I don't know Android Studio and I don't need to enter the coordinates by phone, I already know the coordinates. 
The problem of manual movement will always remain if I do not have the Android App, but I will try to move it through external selectors. 
My intent is to test your project on an existing photovoltaic system where 158 Traker columns with a 30-panel sail are currently installed. 
Currently the trakers have their controller that makes the motors move and through two sensors (10K potentiometer for azimuth and 2-axis sensor for elevation) it controls the movement in the right direction. If I can, I attach the photo of the system. 

<img width="1803" alt="Dome Central" src="https://user-images.githubusercontent.com/62794371/77822242-277aa600-70f1-11ea-80e9-2d91f7b76af1.png">

Thanks 

Fabio

**Comment by graham22** [comment]
Hi Fabio,
I recently setup a slack channel for some of my github projects if you would like to join to see some of the discussions relating to SkyeTracker
[https://join.slack.com/t/classicdiy/shared_invite/zt-czhgndgj-o5RuQ6K6d7yXg309ShXKbQ](url)

I'm working on a new version that uses the ESP32 chip that has MQTT for setup and status.
The code uses astronomical solar tracking so no sensors are required.
The actuators speed and limits are calibrated in the app so position feedback is not required.

Graham
